spring.application.name=eventix_backend
# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8085


# ===============================
# DATABASE CONFIGURATION (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/eventix_db
spring.datasource.username=postgres
spring.datasource.password=master
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
# We use 'validate' because Flyway handles the schema changes (DevOps Best Practice)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY (Database Migrations)
# ===============================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# Show Flyway errors in console
logging.level.org.flywaydb=DEBUG

# ===============================
# SECURITY & JWT (Custom Eventix Settings)
# ===============================
# In production, set JWT_SECRET as an environment variable
eventix.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# 86400000 ms = 24 Hours
eventix.jwt.expiration-ms=86400000

# ===============================
# FILE UPLOAD SETTINGS
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
eventix.upload.directory=./uploads
eventix.upload.max-file-size=5242880

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=INFO
logging.level.com.bpl=DEBUG